DgPadCMS/Areas/Admin/Controllers/UserManageController.cs
using Common;
using DgPadCMS.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DgPadCMS.Areas.Admin.Controllers
{
    
    [Area("Admin")]
    public class UserManageController : Controller
    {
        private readonly UserManager<AppUser> userManager;
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly SignInManager<AppUser> signInManager;
        private IPasswordHasher<AppUser> passwordHasher;
        public UserManageController(RoleManager<IdentityRole> roleManager, SignInManager<AppUser> signInManager, UserManager<AppUser> userManager, IPasswordHasher<AppUser> passwordHasher)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
            this.passwordHasher = passwordHasher;
            this.signInManager = signInManager;
        }

        //View Users Available
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View(userManager.Users);
        }
        //--*--*--//


        //Add New User(s)
        [AllowAnonymous]
        [Authorize(Roles = "Admin")]
        public IActionResult AddUser()
        {
            return View();
        }
        
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AddUser(User user)
        {
            if (ModelState.IsValid)
            {
                AppUser appUser = new AppUser
                {
                    UserName = user.UserName,
                    Email = user.Email
                };

                IdentityResult result = await userManager.CreateAsync(appUser, user.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (IdentityError error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }

            return View(user);
        }
        //--*--*--//
        [Authorize(Roles = "Admin")]
        // Delete
        public async Task<IActionResult> Delete(string id)
        {

            var user = await userManager.FindByIdAsync(id);

            await userManager.DeleteAsync(user);

            return RedirectToAction("Index");
        }
        //**--**--**-

        //LogOut
        
        public ActionResult Logout()
        {
            signInManager.SignOutAsync();
            return RedirectToAction("Login", "User",new { area = "" });
        }


    }

}

DgPadCMS/Areas/Admin/Views/UserManage/AddUser.cshtml
@model Common.User

@{
    ViewData["Title"] = "AddUser";
}

<h1>Add new User</h1>

<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddUser">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br />
<div>
   <button type="button" class="btn btn-danger">
       <a asp-action="Index">Back to List</a>
       </button>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DgPadCMS/Areas/Admin/Views/UserManage/Index.cshtml
@model IEnumerable<Common.AppUser>

@{
    ViewData["Title"] = "Users";
}
<script src="https://www.kryogenix.org/code/browser/sorttable/sorttable.js"></script>
<h1>Users</h1>

<br />
<p>
    <a class="btn btn-outline-success" asp-controller="UserManage" asp-action="AddUser"><i class="bi bi-person-plus-fill"></i> Add User</a>
</p>

<table class="table sortable">
    <thead>
        <tr  class="table-success">
            <th>
                Username
            </th>
            <th>
                Email
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var user in Model) {
        <tr  class="table-light">
            <td>
                @user.UserName
            </td>
            <td>
                @user.Email
            </td>
            <td>

                <a class="btn btn-sm btn-outline-danger" asp-action="Delete" asp-route-id="@user.Id" onclick="return confirm('Are you sure you want to delete this user?');">
                    <i class="bi bi-trash3-fill"></i> </a> 
                


            </td>
        </tr>
}
    </tbody>
</table>

DgPadCMS/Areas/Admin/Views/UserManage/Update.cshtml
@model DgPadCMS.Models.RoleEdit
  
<h1 class="bg-info text-white">Update Role</h1>
<a asp-action="Index" class="btn btn-secondary">Back</a>
<div asp-validation-summary="All" class="text-danger"></div>
  
<form method="post">
    <input type="hidden" name="roleName" value="@Model.Role.Name" />
    <input type="hidden" name="roleId" value="@Model.Role.Id" />
      
    <h2 class="bg-info p-1 text-white">Add To @Model.Role.Name</h2>
    <table class="table table-bordered table-sm">
        @if (Model.NonMembers.Count() == 0)
        {
            <tr><td colspan="2">All Users Are Members</td></tr>
        }
        else
        {
            @foreach (var user in Model.NonMembers)
            {
                <tr>
                    <td>@user.UserName</td>
                    <td>
                        <input type="checkbox" name="AddIds" value="@user.Id">
                    </td>
                </tr>
            }
        }
    </table>
  
    <h2 class="bg-info p-1 text-white">Remove From @Model.Role.Name</h2>
    <table class="table table-bordered table-sm">
        @if (Model.Members.Count() == 0)
        {
            <tr><td colspan="2">No Users Are Members</td></tr>
        }
        else
        {
            @foreach (var user in Model.Members)
            {
                <tr>
                    <td>@user.UserName</td>
                    <td>
                        <input type="checkbox" name="DeleteIds" value="@user.Id">
                    </td>
                </tr>
            }
        }
    </table>
    <button type="submit" class="btn btn-primary">Save</button>
</form>