DgPadCMS/Areas/Admin/Controllers/PostController.cs
using DgPadCMS.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Microsoft.EntityFrameworkCore;
using Common;
using Microsoft.AspNetCore.Authorization;

namespace DgPadCMS.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin,Editor")]
    [Area("Admin")]
    public class PostController : Controller
    {
        private readonly ActionServices services;
        private readonly IWebHostEnvironment webHostEnvironment;
        public List<PostTerm> pterm { get; set; }
        public List<ContentCategory> content { get; set; }
        public PostController( IWebHostEnvironment webHostEnvironment,ActionServices _services)
        {
            this.webHostEnvironment = webHostEnvironment;
            this.services = _services;

        }

        //List Post
        public async Task<IActionResult> Index()
        {
            var postype_tar = services.CheckPostType();
            List<PostType> ptypes = new List<PostType>();
            foreach (PostType i in postype_tar)
            {
                int pid = i.PostTypeId;

                PostType ptype = services.getPostTypeId(pid);

                ptypes.Add(new PostType
                {
                    Title = ptype.Title,
                    PostTypeId = ptype.PostTypeId,
                    TaxonomyId = ptype.TaxonomyId

                });

            }

            ViewBag.Ptypes = ptypes;
           
            var pos =services.OrderPost();

            return View(await pos.ToListAsync());
        }
        //**--**--**--**//

        //Create ------>
        public IActionResult Create(int id)
        {
            createModel pos = new createModel();

            ViewBag.PostTypeId = new SelectList(services.SortPostTypeWhere(id), "PostTypeId", "Title");
            ViewBag.TermId = new SelectList(services.SortTerm(), "TermId", "Name");
            ViewBag.Category = new SelectList(services.GetContentCategory(), "CategoryId", "CategoryName");
            

            return View(); 
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(createModel pos)
        {
            Term ter = new Term();
            PostType ps = new PostType();
            PostTerm pterm = new PostTerm();
            ViewBag.PostTypeId = new SelectList(services.OrderPost(), "PostTypeId", "Title");
            ViewBag.Category = new SelectList(services.GetContentCategory(), "CategoryId", "CategoryName");

            var target_pos = await services.FirstPostTitleAsync(pos.Title);
            if (target_pos != null)
            {
                ModelState.AddModelError("", "This Post already exists.");
                return View(pos);
            }
            string imageName = "NewPNG.png";
            if (pos.ImageUpload != null)
            {
                string uploadsDir = Path.Combine(webHostEnvironment.WebRootPath, "UploadedPhotos");
                imageName = Guid.NewGuid().ToString() + "_" + pos.ImageUpload.FileName;
                string filePath = Path.Combine(uploadsDir, imageName);
                FileStream fs = new FileStream(filePath, FileMode.Create);
                await pos.ImageUpload.CopyToAsync(fs);
                fs.Close();
            }
          
            pos.Image = imageName;

            var localDateTime = DateTime.Now;
            pos.CreationDate = localDateTime;

            //Inserting from ModelView ==> Post Table
            Post post = new Post();
            post.Title = pos.Title;
            post.CreationDate = pos.CreationDate;
            post.PostTypeId = pos.PostTypeId;
            post.Summary = pos.Summary;
            post.Article = pos.Article;
            post.CategoryId = pos.CategoryId;
            post.VideoLink = pos.VideoLink;
            post.AuthorFirst = pos.AuthorFirst;
            post.AuthorLast = pos.AuthorLast;
            post.Image = pos.Image;
            //post.PostId = pos.PostId;
            services.AddPost(post);
            services.DataSave();

            foreach (var id in pos.TermId)
            {
                var poster = new PostTerm()
                {
                    PostId = post.PostId,
                    TermId = id
                };
                services.AddPostTerm(poster);
                services.DataSave();

                //Inserting to PostTerm Table
            }
            await services.DataSaveAsync();

            TempData["Success"] = "This Post has been added!";

            return RedirectToAction("Index");


        }

        //Getting Postype data from Create Post Page
        public async Task < JsonResult> GetSubCategoryByCategoryId(int categoryId)
        {
            List<Term> dat= new List<Term>();
            dat=  services.ListTerms(categoryId);

            List<test> res = new List<test>();
            foreach (Term i in dat)
            {
                String name = i.Name;
                int id = i.TermId;
                res.Add(new test(id, name));
            }
            var json = JsonConvert.SerializeObject(res);
            return Json(json);
        }
        //**--**--**--**//

        //Getting Postype data to Filter Index Page

        public int ShowPType(string PostTypeName)
        {
            var pname = services.FirstPostTypeName(PostTypeName);
            var pid = pname.PostTypeId;

            return pid ;
        }

        // Edit
        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.PostTypeId = new SelectList(services.SortPostTypeViewBag(), "PostTypeId", "Title");
            ViewBag.TermId = new SelectList(services.SortTerm(), "TermId", "Name");
            ViewBag.PostTerms = new SelectList(services.SortPostTypeViewBag(), "TermId", "Name");
            ViewBag.Category = new SelectList(services.GetContentCategory(), "CategoryId", "CategoryName");
            var localDateTime = DateTime.Now;
            Post pos = await services.FindPostIdAsync(id);
            pos.CreationDate = localDateTime;
            if (pos == null)
            {
                return NotFound();
            }
            createModel mm = new createModel();
            pterm = await services.ListPostTerms(id);
            ViewBag.PTerm = pterm;
            //Getting from Post ==> ViewModel
            mm.PostId = id;
            mm.Title = pos.Title;
            mm.CreationDate = pos.CreationDate;
            mm.PostTypeId = pos.PostTypeId;
            mm.Summary = pos.Summary;
            mm.Article = pos.Article;
            mm.AuthorFirst = pos.AuthorFirst;
            mm.AuthorLast = pos.AuthorLast;
            mm.Image = pos.Image;
            mm.CategoryId = pos.CategoryId;
            mm.VideoLink = pos.VideoLink;
           

            return View(mm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Area("Admin")]

        public async Task<IActionResult> Edit(int id, createModel pos)
        {

            ViewBag.PostTypeId = new SelectList(services.SortPostTypeViewBag(), "PostTypeId", "Title");
            ViewBag.TermId = new SelectList(services.SortPostTermViewBag(), "TermId", "Name");
            ViewBag.Category = new SelectList(services.GetContentCategory(), "CategoryId", "CategoryName");
            var target_pos = await services.getPostIdAsync(id);
            
                if (target_pos == null)
                {
                    ModelState.AddModelError("", "The Post doesn't exists.");
                    return View(pos);
                }
                string imageName = "NewPNG.png";
                if (pos.ImageUpload != null)
                {
                    string uploadsDir = Path.Combine(webHostEnvironment.WebRootPath, "UploadedPhotos");

                    if (!string.Equals(pos.Image, "NewPNG.png"))
                    {
                        string oldImagePath = Path.Combine(uploadsDir, pos.Image);
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    imageName = Guid.NewGuid().ToString() + "_" + pos.ImageUpload.FileName;
                    string filePath = Path.Combine(uploadsDir, imageName);
                    FileStream fs = new FileStream(filePath, FileMode.Create);
                    await pos.ImageUpload.CopyToAsync(fs);
                    fs.Close();
                }
                pos.Image = imageName;

                var localDateTime = DateTime.Now;
                pos.CreationDate = localDateTime;
                createModel mm = new createModel();
            //Getting from ModelView ==> Post Table

            target_pos.PostId = pos.PostId;
            target_pos.Title = pos.Title;
            target_pos.CreationDate = pos.CreationDate;
            target_pos.PostTypeId = pos.PostTypeId;
            target_pos.Summary = pos.Summary;
            target_pos.Article = pos.Article;
            target_pos.AuthorFirst = pos.AuthorFirst;
            target_pos.AuthorLast = pos.AuthorLast;
            target_pos.CategoryId = pos.CategoryId;
            target_pos.VideoLink = pos.VideoLink;
            target_pos.Image = pos.Image;
            target_pos.PostTermId = 1;
            services.UpdatePost(target_pos);
            await services.DataSaveAsync();

          /*  foreach (var id1 in pos.TermId)
            {
                PostTerm p = _context.PostTerm.Find(pos.PostId = id);
                p.TermId = id1;
                _context.PostTerm.Update(p);
                _context.SaveChanges();
                //Updating to PostTerm Table
            }*/
            TempData["Success"] = "This Post has been Edited!";
                return RedirectToAction("Index");

        }

        //**--**--**--**//

        // Delete
        public async Task<IActionResult> Delete(int id)
        {

DgPadCMS/Areas/Admin/Controllers/PostTypeController.cs
using Common;
using DgPadCMS.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace DgPadCMS.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class PostTypeController : Controller
    {
        public List<PostType> pos { get; set; }

        private readonly ActionServices services;

        public PostTypeController(ActionServices _services)
        {
            pos = new List<PostType>();
            this.services = _services;
        }

        //List PostType
        public async Task<IActionResult> Index()
        {
            var pos = services.SortPostType();

            return View(await pos.ToListAsync());
        }
        //**--**--**--**//

        //Create
        public IActionResult Create()
        {
            ViewBag.TaxonomyId = new SelectList(services.SortTaxonomyViewBag(), "TaxonomyId", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PostType pos )
        {
            ViewBag.TaxonomyId = new SelectList(services.SortTaxonomyViewBag(), "TaxonomyId", "Name");
            var target_pos = await services.FirstPostTypeTitleAsync(pos.Title);
            if (target_pos != null)
            {
                ModelState.AddModelError("", "The PostType already exists.");
                return View(pos);
            }
            services.AddPostType(pos);
            await services.DataSaveAsync();

            TempData["Success"] = "The PostType has been added!";

            return RedirectToAction("Index");

        }
        //**--**--**--**//

        // Edit
        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.TaxonomyId = new SelectList(services.SortTaxonomyViewBag(), "TaxonomyId", "Name");
            PostType pos = await services.FindPostTypeIdAsync(id);
            if (pos == null)
            {
                return NotFound();
            }

            return View(pos);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, PostType pos)
        {
            ViewBag.TaxonomyId = new SelectList(services.SortTaxonomyViewBag(), "TaxonomyId", "Name");
            var postype = await services.FirstPostTypeIdAsync(id);
            if (postype == null)
            {
                ModelState.AddModelError("", "The PostType already Exists!");
                return View(pos);
            }
            services.UpdatePostType(pos);
            await services.DataSaveAsync();

            TempData["Success"] = "The PostType has been edited!";

            return RedirectToAction("Index");

        }

        //**--**--**--**//

        // Delete
        public async Task<IActionResult> Delete(int id)
        {
            PostType pos = await services.FindPostTypeIdAsync(id);

            if (pos == null)
            {
                TempData["Error"] = "The Postype does not exist!";
            }
            else
            {
                services.RemovePostType(pos);
                await services.DataSaveAsync();

                TempData["Success"] = "The Postype has been deleted!";
            }

            return RedirectToAction("Index");
        }
        //**--**--**--**// 

    }
}

DgPadCMS/Areas/Admin/Controllers/TermController.cs
using Common;
using DgPadCMS.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace DgPadCMS.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class TermController : Controller
    {
        public List<Term> ter { get; set; }

        private readonly ActionServices services;

        public TermController(ActionServices _services )
        {
            ter = new List<Term>();
            this.services = _services;
        }

        //List Term
        public async Task<IActionResult> Index()
        {
            var term = services.SortTermAsc();

            return View(await term);
        }
        //**--**--**--**//

        //Create
        public IActionResult Create()
        {
            ViewBag.TaxonomyId = new SelectList(services.SortTaxonomyViewBag(), "TaxonomyId", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Term term)
        {
            ViewBag.TaxonomyId = new SelectList(services.SortTaxonomyViewBag(), "TaxonomyId", "Name");
            var target_ter = await services.FirstTermName(term.Name);
            if (target_ter != null)
            {
                ModelState.AddModelError("", "The Term already exists.");
                return View(term);
            }

            services.AddTerm(term);
            await services.DataSaveAsync();

            TempData["Success"] = "The Term has been added!";

            return RedirectToAction("Index");

        }
        //**--**--**--**//

        // Edit
        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.TaxonomyId = new SelectList(services.SortTaxonomyViewBag(), "TaxonomyId", "Name");
            Term ter = await services.getTermIdAsync(id);
            if (ter == null)
            {
                return NotFound();
            }

            return View(ter);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Term term)
        {
            ViewBag.TaxonomyId = new SelectList(services.SortTaxonomyViewBag(), "TaxonomyId", "Name");

            var ter = await services.WhereTermIdAsync(id);
            if (ter != null)
            {
                ModelState.AddModelError("", "The Taxonomy already Exists!");
                return View(term);
            }

            services.UpdateTerm(term);
            await services.DataSaveAsync();


            TempData["Success"] = "The Term has been edited!";

           return RedirectToAction("Index");
            
        }

        //**--**--**--**//

        // Delete
        public async Task<IActionResult> Delete(int id)
        {
            Term ter = await services.getTermIdAsync(id);

            if (ter == null)
            {
                TempData["Error"] = "The Term does not exist!";
            }
            else
            {
                services.RemoveTerm(ter);
                await services.DataSaveAsync();

                TempData["Success"] = "The Term has been deleted!";
            }

            return RedirectToAction("Index");
        }
        //**--**--**--**// 

    }
}

DgPadCMS/Areas/Admin/Views/Shared/PartialUser.cshtml
    <li class="navbar-nav navbar-right" style="margin-top:12px">
    <p class="UserLogged">Hi, @User.Identity.Name </p> 
    </li>
    <li class="navbar-nav navbar-right">
        <a asp-area="Admin" asp-controller="UserManage" asp-action="Logout">
        <button class="btn btn-success" data-mdb-ripple-color="white" style="font-size:16px"> Log out</button>
        </a>
   
    </li>
    

DgPadCMS/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] DgPadCMS</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DgPadCMS.styles.css" asp-append-version="true" />
   
   
    <!-- Our Custom CSS -->  
</head>
<body>
    <header>
        @*Aside Nav*@
  <div id="wrapper">
          <nav id="sidebar" >

            <a id="dismiss" href="javascript:void(0)" onclick="closeNav()" style="font-size:30px">&times;</a>
            <div class="sidebar-header">
                 <h4><img style="height:25px;width:25px" src="~/Images/Favicon.png"/>
                 Admin Panel</h4>
            </div>

            <ul class="list-unstyled components">
                <li>
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="bi bi-pin-angle"></i> Post</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a asp-area="Admin" asp-controller="Post" asp-action="Index"><i class="bi bi-files"></i> ALL Posts</a>
                        </li>
                        <li>
                            <a asp-area="Admin" asp-controller="Post" asp-action="Create"><i class="bi bi-plus-circle"></i> Add New</a>
                        </li>
                    </ul>
                   
                </li>
                <li>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="bi bi-stickies"></i> PostTypes</a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a asp-area="Admin" asp-controller="PostType" asp-action="Index"><i class="bi bi-files"></i> ALL PostTypes</a>
                        </li>
                        <li>
                            <a asp-area="Admin" asp-controller="PostType" asp-action="Create"><i class="bi bi-plus-circle"></i> Add New</a>
                        </li>

                    </ul>
                </li>
                <li>
                    <a asp-area="Admin" asp-controller="UserManage" asp-action="Index"><i class="bi bi-people"></i> Users</a>
                </li>
                <li>
                    <a asp-area="Admin" asp-controller="Roles" asp-action="Index"><i class="bi bi-person-workspace"></i> Roles</a>
                </li>
                <li>
                    <a asp-area="Admin" asp-controller="Taxonomy" asp-action="Index"><i class="bi bi-diagram-3"></i> Taxonomy</a>
                </li>
                <li>
                    <a asp-area="Admin" asp-controller="Term" asp-action="Index"><i class="bi bi-check-square"></i> Term</a>
                </li>
                 <li>
                    <a asp-area="Admin" asp-controller="ContentCategory" asp-action="Index"><i class="bi bi-files"></i> Content Category</a>
                </li>
            </ul>
            
         </nav>

  

@*Aside Nav*@
  <div id="content">
    <nav class="navbar navbar-expand-lg navbar-dark" style="border-bottom: 1px solid white">
          <div class="container-fluid">
              <img style="height:40px;width:40px" src="~/Images/Favicon.png"/>
            <a class="navbar-brand" style="font-size:22px"> DgPadCMS</a>
       
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
              <ul class="navbar-nav me-auto">
                  <li>
                       <a asp-area="Admin" asp-controller="Post" asp-action="Index"><i class="bi bi-files"></i> All Posts</a>
                  </li>

              </ul>
                <partial name="PartialUser.cshtml" />
                 @if (User.IsInRole("Admin"))
                 {
              <li class="nav navbar-nav navbar-right">
                   <span id="sidebarCollapse" onclick="openNav()" class="logo-lg"><b><i style="font-size:32px;" class="bi bi-list"></i> </b></span> 
              </li>
                 }
            </div>
          </div>
    </nav>  
</div>
   <div class="overlay" onclick="closeNav()"></div>
</div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jqueryui/jquery-ui.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/ckeditor/ckeditor.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

   

     <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
   
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>
<script type="text/javascript">

     function openNav(){
         $('#sidebar').addClass('active');
            // fade in the overlay
            $('.overlay').addClass('active');
            $('.collapse.in').toggleClass('in');
            $('a[aria-expanded=true]').attr('aria-expanded', 'false');
      // document.getElementById("sidebar").style.width = "240px";

     }
     function closeNav() 
     {

       // document.getElementById("sidebar").style.display = "none";
        $('#sidebar').removeClass('active');
        $('.overlay').removeClass('active');
     }
</script>